[phases.setup]
nixPkgs = ["nodejs", "gcc", "gnumake", "python3"]

[phases.install]
cmds = ["npm install", "cd backend && npm install"]

[phases.build]
cmds = ["cd backend && npm run build"]

[phases.start]
cmd = "cd backend && node dist/server.cjs"
